title: <p align="center"> Kishore Umaprasad </p>
logo: /assets/img/kishore.png
description:  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kishore330033/">LinkedIn</a> |
  <a href="https://github.com/ukishore33">GitHub</a>
 
  <br>  
  ğŸ”­ i'm currently working on violavizn technologies. <br>ğŸ‘¯ i'm looking to collaborate on projects related to combination of Finance, Management, Data Science and  Generative AI related topics. <br>ğŸŒ± I'm currently learning Stock market Analysis and Generative AI. <br>ğŸ’¬ Ask me about Finance, Management, Data Science and  Generative AI related topics. 
  <br>
  </p>

theme: jekyll-theme-minimal
